In [1]:
import torch
print(torch.Tensor([1,2]).cuda())

tensor([1., 2.], device='cuda:0')


In [3]:
x = torch.ones(2,2,requires_grad=True)

In [4]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [5]:
y = x+2
z = y*y*3
out = z.mean()

In [6]:
out.backward()

In [7]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [8]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [9]:
y.grad


/home/gaojing/anaconda3/envs/pytorch-1.7.1/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  """Entry point for launching an IPython kernel.
